# CMake generated Testfile for 
# Source directory: /Users/nielhitesh/LUV---Flicker-
# Build directory: /Users/nielhitesh/LUV---Flicker-/build-phase2
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test([=[test_ai_telemetry]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_ai_telemetry")
set_tests_properties([=[test_ai_telemetry]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_arena]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_arena")
set_tests_properties([=[test_arena]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_execution]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_execution")
set_tests_properties([=[test_execution]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_feed]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_feed")
set_tests_properties([=[test_feed]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_lob]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_lob")
set_tests_properties([=[test_lob]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_stress]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_stress")
set_tests_properties([=[test_stress]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_decoder_fuzz]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_decoder_fuzz")
set_tests_properties([=[test_decoder_fuzz]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_concurrency]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_concurrency")
set_tests_properties([=[test_concurrency]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_ouch_parser]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_ouch_parser")
set_tests_properties([=[test_ouch_parser]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_risk_validator]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_risk_validator")
set_tests_properties([=[test_risk_validator]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_telemetry_export]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_telemetry_export")
set_tests_properties([=[test_telemetry_export]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_crash_recovery]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_crash_recovery")
set_tests_properties([=[test_crash_recovery]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_crash_recovery_process]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_crash_recovery_process")
set_tests_properties([=[test_crash_recovery_process]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_audit_integrity]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_audit_integrity")
set_tests_properties([=[test_audit_integrity]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[test_day4_integration]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/test_day4_integration")
set_tests_properties([=[test_day4_integration]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;81;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
add_test([=[crash_recovery_harness]=] "/Users/nielhitesh/LUV---Flicker-/build-phase2/crash_recovery_harness")
set_tests_properties([=[crash_recovery_harness]=] PROPERTIES  _BACKTRACE_TRIPLES "/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;83;add_test;/Users/nielhitesh/LUV---Flicker-/CMakeLists.txt;0;")
