apiVersion: v1
kind: Service
metadata:
  name: luv-engine-service
  labels:
    app: luv-engine
spec:
  type: ClusterIP
  selector:
    app: luv-engine
  ports:
  - name: metrics
    port: 9100
    targetPort: metrics
  - name: telemetry
    port: 8080
    targetPort: telemetry
